/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#85adff",
        "primary-fixed": "#6e9fff",
        "primary-fixed-dim": "#5391ff",
        "primary-dim": "#699cff",
        "primary-container": "#6e9fff",
        "on-primary": "#002c66",
        "on-primary-fixed": "#00278f",
        "on-primary-fixed-variant": "#002a62",
        "on-primary-container": "#002150",
        secondary: "#8097ff",
        "secondary-fixed": "#c7cfff",
        "secondary-fixed-dim": "#b4c1ff",
        "secondary-dim": "#8097ff",
        "secondary-container": "#c5ceff",
        "on-secondary": "#00175f",
        "on-secondary-fixed": "#00278f",
        "on-secondary-fixed-variant": "#2d48ac",
        "on-secondary-container": "#00175f",
        tertiary: "#e28ce9",
        "tertiary-fixed": "#f5adff",
        "tertiary-fixed-dim": "#e28ce9",
        "tertiary-dim": "#e28ce9",
        "on-tertiary": "#691d74",
        "on-tertiary-fixed": "#3e0047",
        "on-tertiary-fixed-variant": "#681c73",
        "on-tertiary-container": "#5e106a",
        surface: "#0e0e0e",
        "surface-dim": "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#131313",
        "surface-container": "#1a1919",
        "surface-container-high": "#201f1f",
        "surface-container-highest": "#262626",
        "surface-variant": "#262626",
        "on-surface": "#ffffff",
        "on-surface-variant": "#adaaaa",
        "inverse-surface": "#fcf8f8",
        "inverse-on-surface": "#565554",
        "inverse-primary": "#005bc4",
        outline: "#777575",
        "outline-variant": "#494847",
        error: "#ff716c",
        "error-dim": "#d7383b",
        "error-container": "#9f0519",
        "on-error": "#490006",
        "on-error-container": "#ffa8a3",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};