/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background) / <alpha-value>)",
        "background-elevated": "hsl(260 55% 4% / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        card: "hsl(var(--card) / <alpha-value>)",
        "card-foreground": "hsl(var(--card-foreground) / <alpha-value>)",
        popover: "hsl(var(--popover) / <alpha-value>)",
        "popover-foreground": "hsl(var(--popover-foreground) / <alpha-value>)",
        primary: "hsl(var(--primary) / <alpha-value>)",
        "primary-foreground": "hsl(var(--primary-foreground) / <alpha-value>)",
        secondary: "hsl(var(--secondary) / <alpha-value>)",
        "secondary-foreground": "hsl(var(--secondary-foreground) / <alpha-value>)",
        muted: "hsl(var(--muted) / <alpha-value>)",
        "muted-foreground": "hsl(var(--muted-foreground) / <alpha-value>)",
        accent: "hsl(var(--accent) / <alpha-value>)",
        "accent-foreground": "hsl(var(--accent-foreground) / <alpha-value>)",
        destructive: "hsl(var(--destructive) / <alpha-value>)",
        "destructive-foreground": "hsl(var(--destructive-foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        "border-strong": "hsl(240 4% 26% / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
        hero: {
          heading: "hsl(var(--hero-heading) / <alpha-value>)",
          sub: "hsl(var(--hero-sub) / <alpha-value>)",
        },
        text: "hsl(var(--foreground) / <alpha-value>)",
        "text-muted": "hsl(var(--muted-foreground) / <alpha-value>)",
        "text-dim": "hsl(240 4% 48% / <alpha-value>)",
        dim: "hsl(var(--muted-foreground) / <alpha-value>)",
        success: "hsl(145 73% 55% / <alpha-value>)",
        warning: "hsl(83 82% 55% / <alpha-value>)",
        danger: "hsl(var(--destructive) / <alpha-value>)",
        surface: "hsl(var(--card) / <alpha-value>)",
        "surface-strong": "hsl(240 6% 12% / <alpha-value>)",
        "surface-muted": "hsl(var(--muted) / <alpha-value>)",
        "accent-strong": "hsl(262 83% 52% / <alpha-value>)",
        "accent-soft": "hsl(262 83% 70% / <alpha-value>)",
      },
      fontFamily: {
        sans: ["'Geist Sans'", "Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "var(--radius)",
        lg: "calc(var(--radius) - 2px)",
        xl: "var(--radius)",
        full: "9999px",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        marquee: "marquee 20s linear infinite",
      },
    },
  },
  plugins: [],
};
